# Generated by Django 2.2.12 on 2020-05-02 23:39

import creditcards.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_location', models.CharField(max_length=200)),
                ('rental_location_address', models.CharField(max_length=200)),
                ('vehicle_capacity', models.IntegerField()),
                ('no_of_vehicles', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('vin_no', models.CharField(max_length=200)),
                ('reservation_datetime', models.DateTimeField()),
                ('rental_location', models.CharField(max_length=200)),
                ('return_datetime', models.DateTimeField()),
                ('rental_charge', models.CharField(max_length=100)),
                ('actual_returntime', models.DateTimeField()),
                ('reservation_status', models.CharField(choices=[('BKD', 'BOOKED'), ('RNT', 'RENTED'), ('RTD', 'RETURNED')], default='BKD', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('SC', 'Small Car'), ('FSC', 'Full Size Car'), ('TR', 'Truck'), ('LC', 'Luxury Car')], default='SC', max_length=3)),
                ('make_model', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('vin_no', models.CharField(max_length=50)),
                ('registration_tag', models.CharField(max_length=20)),
                ('current_mileage', models.IntegerField()),
                ('last_service_time', models.DateField()),
                ('basic_fee', models.IntegerField()),
                ('advanced_fee', models.IntegerField()),
                ('late_fee', models.IntegerField()),
                ('vehicle_condition', models.CharField(choices=[('GD', 'Good'), ('NC', 'Needs Cleaning'), ('NM', 'Needs Maintenance')], default='GD', max_length=2)),
                ('rental_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zip.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.TextField(max_length=200)),
                ('vehicle_condition', models.CharField(choices=[('GD', 'Good'), ('NC', 'Needs Cleaning'), ('NM', 'Needs Maintenance')], default='GD', max_length=2)),
                ('reservation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zip.Reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email_id', models.EmailField(max_length=200)),
                ('driver_license_state', models.CharField(max_length=10)),
                ('driving_license_no', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('residence_address', models.CharField(max_length=500)),
                ('cc_holder_name', models.CharField(max_length=200)),
                ('cc_number', creditcards.models.CardNumberField(max_length=25, verbose_name='Card Number')),
                ('cc_expiry', creditcards.models.CardExpiryField(verbose_name='Expiration Date')),
                ('cc_code', creditcards.models.SecurityCodeField(max_length=4, verbose_name='Security Code')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
